use_frameworks!

target 'MusicoAudioPlayer_Example' do
    pod 'MusicoAudioPlayer', :path => '../'
    pod 'SDWebImage', '~>3.8'
    
    target 'MusicoAudioPlayer_Tests' do
        inherit! :search_paths
    end
end
